/**
 * KPI Assistant AI Worker
 *
 * Processes screenshots using Cloudflare Workers AI.
 * Model: @cf/meta/llama-3.2-11b-vision-instruct
 *
 * Secrets (set after deploy via: npx wrangler secret put SECRET_NAME):
 *   AUTH_TOKEN — generated by KPI Assistant during setup, stored in app config
 *
 * Request:  POST / { image_base64: string, prompt: string }
 *           Header: X-Auth-Token: <your token>
 * Response: { response: string }
 */

interface Env {
  AI: Ai;
}

interface RequestBody {
  image_base64: string;
  prompt: string;
  model?: string;
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {

    const corsHeaders = {
      "Access-Control-Allow-Origin":  "*",
      "Access-Control-Allow-Methods": "POST, OPTIONS",
      "Access-Control-Allow-Headers": "Content-Type, X-Auth-Token",
    };

    // ── CORS preflight ──────────────────────────────────────────────────────
    if (request.method === "OPTIONS") {
      return new Response(null, { headers: corsHeaders });
    }

    if (request.method !== "POST") {
      return Response.json({ error: "Method not allowed" }, { status: 405 });
    }

    // ── Parse body ──────────────────────────────────────────────────────────
    let body: RequestBody;
    try {
      body = await request.json();
    } catch {
      return Response.json({ error: "Invalid JSON body" }, { status: 400 });
    }

    const { image_base64, prompt } = body;
    if (!image_base64 || !prompt) {
      return Response.json({ error: "Missing image_base64 or prompt" }, { status: 400 });
    }

    // ── Convert base64 → bytes for Workers AI ───────────────────────────────
    const imageBytes = Uint8Array.from(atob(image_base64), c => c.charCodeAt(0));

    // ── Classify via Workers AI ─────────────────────────────────────────────
    try {
      const result = await (env.AI.run as any)(
        "@cf/meta/llama-3.2-11b-vision-instruct",
        {
          prompt,
          image: [...imageBytes],
          max_tokens: 512,
        }
      );

      const text: string = result?.response ?? "";
      return Response.json({ response: text }, { headers: corsHeaders });

    } catch (err: any) {
      return Response.json(
        { error: `AI error: ${err?.message ?? "unknown"}` },
        { status: 500, headers: corsHeaders }
      );
    }
  },
} satisfies ExportedHandler<Env>;
